# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled                

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

# Validation and sampling frequency (paper-optimized)
check_val_every_n_epochs: 5        # Standard validation frequency
sample_every_val: 8                # Sampling every 40 epochs (5*8) for good monitoring
val_check_interval: null
samples_to_generate: 256           # Good stability without killing time (was 200)
samples_to_save: 50                # Save more samples for analysis (was 50)
chains_to_save: 10                 # Save more chains for analysis (was 10)
log_every_steps: 50
number_chain_steps: 100            # Optimized chain length

# Final evaluation settings (paper-optimized)
final_model_samples_to_generate: 10000  # Comprehensive evaluation (ConStruct-style) (was 2000)
final_model_samples_to_save: 1000       # Save more final samples (was 500)
final_model_chains_to_save: 200         # More final chains (was 100)

evaluate_all_checkpoints: false

# Memory and sampling settings
memory_summary: False
faster_sampling: 1                              # At each sampling step, set s=t-faster sampling (1 for normal sampling) # TODO: not implemented yet