# General settings
name: 'graph-tf-model'      # Warning: 'debug' and 'test' are reserved name that have a special behavior

wandb: 'online'             # online | offline | disabled                

resume: null            # If resume, path to ckpt file from outputs directory in main directory
test_only: null         # Use absolute path

check_val_every_n_epochs: 20      # More frequent validation for better monitoring
sample_every_val: 5                # More frequent sampling for evaluation
val_check_interval: null
samples_to_generate: 1000          # More samples for better evaluation (thesis setting)
samples_to_save: 200               # Save more samples for analysis (thesis setting)
chains_to_save: 10                 # Save more chains for analysis (thesis setting)
log_every_steps: 50
number_chain_steps: 200            # Longer chains for better visualization (thesis setting)

final_model_samples_to_generate: 2000  # Comprehensive final evaluation (thesis setting)
final_model_samples_to_save: 500       # Save more final samples (thesis setting)
final_model_chains_to_save: 100        # More final chains (thesis setting)

evaluate_all_checkpoints: False

memory_summary: False
faster_sampling: 1                              # At each sampling step, set s=t-faster sampling (1 for normal sampling) # TODO: not implemented yet