# Model settings
transition: 'absorbing_edges'                          # uniform, marginal, planar, absorbing_edges, # edge_insertion COMMENTED OUT
diffusion_steps: 500
n_layers: 5

# Constraint settings (ConStruct philosophy)
rev_proj: null  # planar, tree, lobster, ring_count_at_most, ring_count_at_least, ring_length_at_most, ring_length_at_least

# Edge-deletion constraints (use with absorbing_edges transition)
max_rings: 0     # For ring_count_at_most: maximum number of rings allowed
use_incremental: True  # For ring_count_at_most: use efficient incremental mode (True) or baseline mode (False)
max_ring_length: 6  # For ring_length_at_most: maximum ring size allowed
use_incremental_length: True  # For ring_length_at_most: use efficient incremental mode (True) or baseline mode (False)

# Edge-insertion constraints (use with edge_insertion transition) - COMMENTED OUT
# min_rings: 2     # For ring_count_at_least: minimum number of rings required
# min_ring_length: 4  # For ring_length_at_least: minimum ring size required


# Extra features
extra_features: True
eigenfeatures: True
max_degree: 10  # for degree distribution
num_eigenvectors: 5
num_eigenvalues: 9
num_degree: 10  # for powers of adjacency matrix

extra_molecular_features: True

# Do not set hidden_mlp_E, dim_ffE too high, computing large tensors on the edges is costly
# At the moment (03/08), y contains quite little information
hidden_mlp_dims: {'X': 256, 'E': 128, 'y': 128}

# The dimensions should satisfy dx % n_head == 0
hidden_dims : {'dx': 256, 'de': 64, 'dy': 64, 'n_head': 8, 'dim_ffX': 256, 'dim_ffE': 128, 'dim_ffy': 128}

lambda_train: [1, 2, 5, 0]      # X, C, E, y

nu:
  x: 1
  c: 1
  e: 1
  y: 1

dropout: 0.1
dropout_in_and_out: False
cycle_features: True