# QM9 molecular dataset
name: qm9
remove_h: true
datadir: 'data/qm9'
#subset: 10  # Use only 10 samples per split for minimal run
target_prop: null          # no property conditioning
batch_size: 128
num_workers: 4             # adjust to your CPU


"""
from digress:

name: 'qm9'            # qm9, qm9_positional
datadir: 'data/qm9/qm9_pyg/'
remove_h: True
random_subset: null
pin_memory: False
"""
