# QM9 molecular dataset
name: qm9
remove_h: true
datadir: 'data/qm9'
target_prop: null          # no property conditioning
batch_size: 64             # consistent with experiment config
num_workers: 4             # adjust to your CPU


