# QM9 molecular dataset
name: qm9
remove_h: true
datadir: 'data/qm9'
#subset: 10  # Use only 10 samples per split for minimal run
target_prop: null          # no property conditioning
batch_size: 128
num_workers: 4             # adjust to your CPU
